NordicSemiconductor/pc-nrfconnect-toolchain-manager

- src/InstallDir/InstallDirDialog.jsx
- src/Manager/Environment/EnvironmentMenu.jsx
- src/Manager/Environment/environmentEffects.js
This is part of fixing [NCP-2997](https://projecttools.nordicsemi.no/jira/browse/NCP-2997).
The previous implementation sometimes corrupted the installation. The new implementation does respect whether a new NCS is installed or whether it is just updated. In the latter case, a possibly existing directory `.west` must not be removed and the script `ncsmgr init-ncs` should not call `west init`. For this, the new implementation requires an updated version of the toolchain, that honors passing the parameter `--just-update` to the script `ncsmgr init-ncs`. This update is implemented in NordicPlayground/toolchain#26.
This new implementation follows the logic as described in
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/gs_installing.html#updating-the-repositories
With this …
> Fix updating ncs

- Changelog.md
- package.json
- src/Manager/Environment/EnvironmentMenu.jsx
- src/Manager/Environment/Install.jsx
- src/Manager/Environment/environmentEffects.js
- src/Manager/Environment/environmentPropType.jsx
- src/Manager/Environment/environmentReducer.js
- src/Manager/Environment/segger.js
- src/Manager/Environment/segger.test.js
- src/Manager/Manager.jsx
- src/Manager/initEnvironments.js
- src/Manager/managerReducer.js
- src/NrfCard/nrfCard.scss
- src/Settings/Settings.jsx
- src/persistentStore.js
This PR adds macOS support to Toolchain Manager
- separate json file is used as index to the toolchain bundles
- master environment is hidden by default and can be explicitly enabled in the settings
- changing base directory is disabled, since due to the way brew hardwires installation paths in binaries 
At the time of this PR the _master_ toolchain is not available for Windows, and the is the only available toolchain for macOS.
> Add macOS support

- Changelog.md
- src/Manager/Environment/environmentEffects.js
This PR adds functionality to automatically install the cmake support module that is bundled with the toolchain.
> Install cmake support module

- src/Manager/Environment/EnvironmentMenu.jsx
- src/Manager/Environment/environmentEffects.js
- src/Manager/Environment/segger.js
- src/Settings/Settings.jsx
- src/persistentStore.js
Since there's a difference in the NCS tag/version (e.g. 'v1.4.0-rc1') and the snap version which does not allow dots: i.e. 'v140-rc1', the reference to the snap installation needs some adjustments.
For this to work the toolchain build will be updated.
> Fix linux environment

- Changelog.md
- azure-pipelines.yml
- src/Manager/Environment/environmentEffects.js
This PR reverts the functionality of installing the cmake packages, since it is now included in the init-ncs script carried by the toolchain.
> Remove cmake package install

- Changelog.md
- src/Manager/Environment/EnvironmentMenu.jsx
- src/Manager/Manager.jsx
- src/Manager/PlatformInstructions.jsx
Due to the limitations of the current solution of the toolchain package for linux the support for it in toolchain manager shall be disabled for now.
> Disable linux environment

- Changelog.md
- package.json
- src/Manager/Environment/environmentEffects.js
- src/style.scss
This PR on macOS fixes the missing `~/.cmake/packages/...` after the SDK repositories are cloned. The issue is caused by missing HOME environment variable in electron's sandboxed child process.
Already installed environments can also be fixed just by _Update SDK_ submenu command, which will execute the same script.
> Fix cmake configuration issue on macOS

- Changelog.md
- package.json
- src/Manager/Environment/ShowFirstSteps.jsx
- src/Manager/Environment/environmentEffects.js
- src/Manager/Manager.jsx
- src/ReduxConfirmDialog/ReduxConfirmDialog.jsx
- src/ReduxConfirmDialog/reduxConfirmDialogReducer.js
This PR tries to prevent that the west clone procedure breaks, which would in case a higher level `.west` folder exists.
Prior installation procedure all parent folders are checked and the user is informed and instructed to remove these folders.
The first steps screen is also disabled during installation since it breaks the installation workflow and introduces further inconsistencies.
> Dialog and instructions to remove directories that would block installation

- Changelog.md
Because it does not describe a change that is visible to the users.
> Remove changelog entry

- src/Manager/Environment/EnvironmentMenu.jsx
This fixes [NCP-3761](https://projecttools.nordicsemi.no/jira/browse/NCP-3761):
Strangely, /usr/local/bin is not in the PATH by default when we open
a terminal from an application. But it being in the path is expected
for many cases, e.g. when nrfjprog is placed there. homebrew is usually
also found in /usr/local/bin
> Fix path on macOS

- src/Manager/Manager.tsx
Fixes [this](https://trello.com/c/E5HxyMfO/214-while-installing-a-toolchain-clicking-on-first-steps-to-build-hides-the-installation-progress)
> fix: init environments at app start only

- src/Manager/Manager.tsx
- src/Manager/versionFilter.test.ts
- src/Manager/versionFilter.ts
- src/Settings/Settings.tsx
- src/Settings/settingsSlice.ts
Allow toolchain manager to have non-semver versions of environments. 
Removed hiding of master as it is no longer available for mac and windows.
> Allow non-semver versions

- src/Manager/Manager.tsx
- src/Settings/Settings.tsx
- src/style.scss
Used a custom className instead of using a shared one. This will make it so the About pane is not restricted in width.
Changed it due to a new feature from shared which would otherwise squish the cards in the About pane: https://github.com/NordicSemiconductor/pc-nrfconnect-shared/pull/200
> style: use a custom className instead of overwriting a shared one

- package.json
This app currently needs `shared` 5.10.0 and thus also needs at least 3.9.2 of the engine.
> Fix required engine version

- Changelog.md
- src/Manager/Manager.tsx
- src/Manager/detectMultipleInstallDirs.ts
- src/ReduxConfirmDialog/ReduxConfirmDialog.tsx
- src/ReduxConfirmDialog/reduxConfirmDialogSlice.ts
- src/persistentStore.ts
When people used the TM on Windows before 1.0.0, their SDK environments were by default installed to `%USERPROFILE%\ncs`. If they never changed that default install directory and upgraded the TM to 1.0.0 they did not see their installed SDK environments any longer because now `C:/ncs` is used for their environments. 
(This did not happen on macOS or if the users ever changed their installation directory.)
The new behaviour: 
1. If users have SDK environments in `%USERPROFILE%\ncs` but **not** yet in `C:/ncs` then continue to use the old `%USERPROFILE%\ncs`.
2. If users have **no** SDK environments in `%USERPROFILE%\ncs` but already in `C:/ncs` then continue to use the new `C:/ncs`.
3. If users already have SDK environments in both,`%USERPROFILE%\ncs` and `C:/ncs`, then show them this …
> Fix: Missing existing environments on Windows

- src/persistentStore.ts
Fixes the issue that [on Windows another directory than `C:\ncs` might be used as default install dir](https://github.com/NordicSemiconductor/pc-nrfconnect-toolchain-manager/pull/165#pullrequestreview-1025988626).
Also restructures some things: 
* Move code from top level into functions.
* Consistently let the folders be created by `path.resolve`.
* Only have one mention of `path.resolve` instead of multiple.
> Enhance fallback install dir

- package.json
The caret was wrong because we expect the app to continue to work with also future major versions like `4.0.0`.
> Correct engine specification

- Changelog.md
- package.json
- src/Manager/nrfutil/nrfutilChildProcess.ts
After spreading process.env only `Path` was a valid property. Since we used `PATH` as a getter we ended up with `undefined` in the final path environment variable.
> fix: Path environment variable was incomplete and wrong on windows

- Changelog.md
- README.md
- src/FirstInstall/FirstInstallInstructions.tsx
- src/Manager/Environment/ShowFirstSteps.tsx
- src/Manager/PlatformInstructions.tsx
Replaced Infocenter links with TechDocs ones.
> doc: replace Infocenter links

- src/persistentStore.ts
For [NCD-1118](https://nordicsemi.atlassian.net/browse/NCD-1118):
Get legacy toolchains (for NCS 1.x) from Artifactory. Users usually will not care about this, so it is not added to the changelog.
Also removed the unused method `setToolchainIndexUrl`.
> Use Artifactory for legacy toolchains
