NordicSemiconductor/pc-nrfconnect-toolchain-manager

- Changelog.md
- package.json
- src/InstallPackageDialog/InstallPackageDialog.jsx
- src/Manager/Environment/environmentEffects.js
- src/Manager/Manager.jsx
- src/Manager/managerReducer.js
- src/Manager/managerReducer.test.js
This PR introduces the possibility of installing a toolchain from local file or from URL.
Added support for drag-and-drop for both files and the URL.
> Feature: install package

- src/InstallDir/InstallDirDialog.jsx
- src/Manager/Environment/Install.jsx
- src/Manager/Environment/RemoveEnvironmentDialog.jsx
- src/Manager/Environment/environmentEffects.js
- src/Manager/Environment/environmentReducer.js
- src/Manager/managerReducer.js
This PR adds error dialogs should download or install fail.
The way functions are dispatched rather than called with dispatch is updated to follow the convention.
The environment state is updated with a stage and accessor functions are simplified to avoid complicated logic and unnecessary calls.
> Add error dialogs and clean redux workflow

- src/Manager/Environment/EnvironmentMenu.tsx
A copy of #86 for the master branch.
> Fix path on macOS

- Changelog.md
Forgot that in the PR before. Also fixed the changelog format.
> Describe fix to macOS path

- src/Settings/Settings.tsx
> Use toggles from shared

- src/Manager/Environment/ShowFirstSteps.tsx
There was a request to enable the use of this button already during install.
> feat: enable first steps button during install

- src/Manager/Environment/effects/installEnvironment.ts
Signed-off-by: Pascal Pickel <Pascal.Pickel@nordicsemi.no>
> fix: update vs code status when installing toolchain

- Changelog.md
Signed-off-by: Pascal Pickel <Pascal.Pickel@nordicsemi.no>
> docs: remove entry about new tests from changelog

- Changelog.md
- src/Manager/Environment/style.scss
> Change color install progress

- Changelog.md
- package-lock.json
- package.json
- src/Manager/Environment/EnvironmentMenu.tsx
> Replace openItem with the new openPath

- Changelog.md
- package-lock.json
- package.json
- src/Manager/Environment/EnvironmentMenu.tsx
> Prepare release

- azure-pipelines.yml
> Update references to main

- ,
- Changelog.md
- README.md
- azure-pipelines.yml
- jest.config.js
- package-lock.json
- package.json
- src/InstallDir/installDirSlice.ts
- src/Manager/Environment/environmentReducer.ts
- src/Manager/managerSlice.ts
- src/Manager/versionFilter.ts
- src/ReduxConfirmDialog/reduxConfirmDialogSlice.ts
- src/Settings/settingsSlice.ts
- src/ToolchainSource/toolchainSourceSlice.ts
- src/VsCodeDialog/VsCodeDialog.tsx
- src/VsCodeDialog/vscodeSlice.ts
- src/persistentStore.ts
- tsconfig.json
- webpack.config.js
> uppdate to shared 6

- ,
> refactor: remove file that was accidentally added

- Changelog.md
- src/Manager/Environment/effects/cloneNcs.ts
> Log complete repository name

- Changelog.md
- src/Manager/nrfutil/terminal.ts
- src/Manager/sdkPath.ts
> Pass zephyr environment to terminal

- Changelog.md
- src/Manager/Environment/EnvironmentMenu.tsx
- src/Manager/nrfutil/terminal.ts
> Support for gnome-terminal

- src/Manager/Environment/Install.tsx
> Fix cancel button visibility

- src/Manager/versionFilter.test.ts
- src/Manager/versionFilter.ts
> Don't filter prerelease if there is no release yet.

- Changelog.md
- src/Manager/nrfutil/west.ts
> Prevent west update from freezing.

- Changelog.md
- package-lock.json
- package.json
- src/persistentStore.ts
> Show message if failing to run nrfutil

- Changelog.md
- src/Manager/Environment/effects/installPackage.ts
- src/Manager/initEnvironments.ts
- src/Manager/managerSlice.ts
- src/Manager/nrfutil/nrfutilChildProcess.ts
If the internet connection was missing, no nrfutil toolchains would be listed as it would also abort the list call.
> fix: split list and search into separate try catch

- package-lock.json
- package.json
- src/types.d.ts
The previously used version of shared used an outdated publish script and so needs to be updated before publishing a new version.
> Update shared to v18

- src/InstallDir/InstallDirDialog.tsx
- src/InstallDir/installDirSlice.ts
- src/Manager/Environment/EnvironmentMenu.tsx
- src/Manager/Environment/effects/cloneNcs.ts
- src/Manager/Environment/effects/downloadToolchain.ts
- src/Manager/Environment/effects/helpers.ts
- src/Manager/Environment/effects/installEnvironment.ts
- src/Manager/Environment/effects/installPackage.ts
- src/Manager/Environment/effects/installToolchain.ts
- src/Manager/Environment/effects/removeEnvironment.ts
- src/Manager/Manager.tsx
- src/Manager/ToolchainManager/env.ts
- src/Manager/ToolchainManager/install.ts
- src/Manager/ToolchainManager/list.ts
- src/Manager/ToolchainManager/search.ts
- src/Manager/ToolchainManager/terminal.ts
- src/Manager/ToolchainManager/uninstall.ts
- src/Manager/ToolchainManager/west.ts
- src/Manager/detectMultipleInstallDirs.ts
- src/Manager/initEnvironments.ts
- src/Manager/nrfutil/envAsScript.ts
- src/Manager/sdkPath.ts
- src/Manager/toolchainPath.ts
- src/ToolchainSource/ToolchainSourceDialog.tsx
- src/index.tsx
- src/persistentStore.ts
> fix: make install dir optional and use nrfutil for fallback

- package-lock.json
- package.json
> feat: update shared

- package-lock.json
- package.json
- tailwind.config.js
> fix: don't disable preflight in tailwind config

- src/Manager/Environment/effects/installEnvironment.ts
> fix: don't show error when user cancels install

- src/VsCodeDialog/VsCodeDialog.tsx
> style: convert VS Code Dialog to new design

- package-lock.json
- package.json
> Fix: App can freeze when closing while waiting for usage data to send

- package.json
> feat: update nrfutil version

- Changelog.md
- package-lock.json
- package.json
> Update nrfutil toolchain-manager

- Changelog.md
- src/VsCodeDialog/vscode.ts
> Fix: user vscode url to open vscode

- Changelog.md
- src/Manager/Environment/Environment.tsx
- src/Manager/Environment/Install.tsx
> Feat: add warning for NCS 2.7

- package.json
> Update toolchain manager cli

- Changelog.md
- package-lock.json
> Release 1.5.0: prepare 

- package.json
Reverts NordicSemiconductor/pc-nrfconnect-toolchain-manager#254
> Revert "Update toolchain manager cli"

- src/VsCodeDialog/VsCodeDialog.tsx
> Fix: skip on command line dialog looping and reopening dialog

- Changelog.md
Unfortunately fix isn't applicable to Windows and requires further investigation
> Clarify changelog for 1.5.0 fix

- Changelog.md
- package-lock.json
- package.json
> Release 1.6.0 prepare
